# Seoul Subway Station Orders
# Keyed by RouteNameEn exactly as it appears in CARD_SUBWAY_MONTH_202512.csv
# Station names match StationNameEn from the CSV.
# Sources: yometro.com, metrolinehub.com, Wikipedia (scraped March 2026)
#
# USAGE:
#   from seoul_station_orders import STATION_ORDER
#   # Returns dict: { 'Line 1': ['City Hall', 'Jonggak', ...], ... }
#   # Use to sort stations within each line before building graph edges.
#
# NOTES ON LINE 1 BRANCHES:
#   The CSV splits Line 1 into several route names. The full combined order
#   (used as the single '1호선' / 'Line 1' key below) merges all branches.
#   Separate branch keys are also provided for the CSV's sub-entries:
#     - 'Line 1'          → core trunk: Soyosan ↔ Incheon
#     - 'Gyeongbu Line'   → Guro ↔ Sinchang (Janghang) branch
#     - 'Gyeongwon Line'  → Hoegi ↔ Yeoncheon branch (부분; in 경원선 CSV entry)
#     - 'Line 1' (경인선)  → see note in module docstring
#
# WARNING: 경인선 is mislabeled as 'Line 1' in the CSV. Use 'RouteName' (Korean)
#          to distinguish it from 1호선 (also 'Line 1').

STATION_ORDER = {

    # ── 1호선 (Line 1) ─────────────────────────────────────────────────────
    # Core trunk: Soyosan → Incheon
    "Line 1": [
        "Soyosan",
        "Dongducheon",
        "Bosan",
        "Dongducheon Jungang",
        "Jihaeng",
        "Deokjeong",
        "Deokgye",
        "Yangju",
        "Nogyang",
        "Ganeung",
        "Uijeongbu",
        "Hoeryong",
        "Mangwolsa",
        "Dobongsan",
        "Dobong",
        "Banghak",
        "Chang-dong",
        "Nokcheon",
        "Wolgye",
        "Kwangwoon Univ.",
        "Seokgye",
        "Sinimun",
        "Hankuk Univ. of Foreign Studies",
        "Hoegi",
        "Cheongnyangni (University of Seoul)",
        "Jegi-dong",
        "Sinseol-dong",
        "Dongmyo",
        "Dongdaemun",
        "Jongno 5(o)-ga",
        "Jongno 3(sam)-ga",
        "Jonggak",
        "City Hall",
        "Seoul Station",
        "Namyeong",
        "Yongsan",
        "Noryangjin",
        "Daebang",
        "Singil",
        "Yeongdeungpo",
        "Sindorim",
        "Guro",
        "Guil",
        "Gaebong",
        "Oryudong",
        "Onsu (Sungkonghoe Univ.)",
        "Yeokgok",
        "Sosa",
        "Bucheon",
        "Jung-dong",
        "Songnae",
        "Bugae",
        "Bupyeong",
        "Baegun",
        "Dongam",
        "Ganseok",
        "Juan",
        "Dohwa",
        "Jemulpo",
        "Dowon",
        "Dongincheon",
        "Incheon",
    ],

    # 경부선 (Gyeongbu Line) — Guro south to Sinchang via Cheonan
    "Gyeongbu Line": [
        "Guro",
        "Gasan Digital Complex",
        "Doksan",
        "Geumcheon-gu Office",
        "Seoksu",
        "Gwanak",
        "Anyang",
        "Myeonghak",
        "Geumjeong",
        "Gunpo",
        "Dangjeong",
        "Uiwang",
        "Sungkyunkwan Univ.",
        "Hwaseo",
        "Suwon",
        "Seryu",
        "Byeongjeom",
        "Sema",
        "Osan Univ.",
        "Osan",
        "Jinwi",
        "Songtan",
        "Seojeong-ri",
        "Pyeongtaek Jije",
        "Pyeongtaek",
        "Seonghwan",
        "Jiksan",
        "Dujeong",
        "Cheonan",
        "Bongmyeong",
        "Ssangyong (Nazareth Univ.)",
        "Asan",
        "Tangjeong",
        "Baebang",
        "Onyang Oncheon",
        "Sinchang (Soonchunhyang Univ.)",
    ],

    # 경원선 (Gyeongwon Line) — Hoegi → Yeoncheon
    # (runs as part of Line 1 through-service)
    "Gyeongwon Line": [
        "Hoegi",
        "Kwangwoon Univ.",
        "Seokgye",
        "Sinimun",
        "Hankuk Univ. of Foreign Studies",
        "Cheongnyangni (University of Seoul)",
        "Jegi-dong",
        "Sinseol-dong",
        "Dongmyo",
        "Dobong",
        "Banghak",
        "Chang-dong",
        "Nokcheon",
        "Wolgye",
        "Mangwolsa",
        "Hoeryong",
        "Uijeongbu",
        "Ganeung",
        "Nogyang",
        "Yangju",
        "Deokgye",
        "Deokjeong",
        "Jihaeng",
        "Dongducheon Jungang",
        "Bosan",
        "Dongducheon",
        "Soyosan",
        "Cheongsan",
        "Jeongok",
        "Yeoncheon",
    ],

    # 경인선 (Gyeongin Line) — mislabeled "Line 1" in CSV; Guro → Incheon
    # NOTE: In the CSV, RouteName=경인선, RouteNameEn='Line 1'
    # Distinguish using the Korean column. Covered by main Line 1 key above,
    # but listed separately here for reference.
    # (No separate key needed if you use Korean RouteName as graph key.)

    # ── 2호선 (Line 2) ─────────────────────────────────────────────────────
    "Line 2": [
        "City Hall",
        "Euljiro 1(il)-ga",
        "Euljiro 3(sam)-ga",
        "Euljiro 4(sa)-ga",
        "Dongdaemun History & Culture Park (DDP)",
        "Sindang",
        "Sangwangsimni",
        "Wangsimni (Seongdong-gu Office)",
        "Hanyang University",
        "Ttukseom",
        "Seongsu",
        "Konkuk Univ",
        "Guui (Gwangjin-gu Office)",
        "Gangbyeon (East Seoul Bus Terminal)",
        "Jamsilnaru",
        "Jamsil (Songpa-gu Office)",
        "Jamsilsaenae",
        "Sports Complex",
        "Samseong (World Trade Center)",
        "Seolleung",
        "Yeoksam",
        "Gangnam",
        "Seoul Nat'l Univ. of Education",
        "Seocho",
        "Bangbae",
        "Sadang",
        "Nakseongdae (Gang Gam-chan)",
        "Seoul Nat'l Univ. (Gwanak-gu Office)",
        "Bongcheon",
        "Sillim",
        "Sindaebang",
        "Guro Digital Complex",
        "Daerim (Guro-gu Office)",
        "Sindorim",
        "Mullae",
        "Yeongdeungpo District Office",
        "Dangsan",
        "Hapjeong",
        "Hongik University",
        "Sinchon",
        "Ewha Womans University",
        "Ahyeon",
        "Chungjeongno (Kyonggi Univ.)",
        # loop continues back to City Hall; branch lines below:
        # Seongsu branch: Seongsu → Sinseol-dong
        "Yongdap",
        "Sindap",
        # Sinjeong branch: Sindorim → Kkachisan
        "Dorimcheon",
        "Yangcheon-gu Office",
        "Sinjeongnegeori",
        "Sinjeong (Bank Area)",
        "Kkachisan",
    ],

    # ── 3호선 (Line 3) ─────────────────────────────────────────────────────
    "Line 3": [
        "Daehwa",
        "Juyeop",
        "Jeongbalsan",
        "Madu",
        "Baekseok",
        "Daegok",
        "Hwajeong",
        "Wondang",
        "Wonheung",
        "Samsong",
        "Jichuk",
        "Gupabal",
        "Yeonsinnae",
        "Bulgwang",
        "Nokbeon",
        "Hongje",
        "Muakjae",
        "Dongnimmun",
        "Gyeongbokgung (Government Complex Seoul)",
        "Anguk",
        "Jongno 3(sam)-ga",
        "Euljiro 3(sam)-ga",
        "Chungmuro",
        "Dongguk Univ",
        "Yaksu",
        "Geumho",
        "Oksu",
        "Apgujeong",
        "Sinsa",
        "Jamwon",
        "Express Bus Terminal",
        "Seoul Nat'l Univ. of Education",
        "Nambu Bus Terminal (Seoul Arts Center)",
        "Yangjae (Seocho-gu Office)",
        "Maebong",
        "Dogok",
        "Daechi",
        "Hangnyeoul",
        "Daecheong",
        "Irwon",
        "Suseo",
        "Garak Market",
        "Police Hospital",
        "Ogeum",
    ],

    # ── 4호선 (Line 4) ─────────────────────────────────────────────────────
    "Line 4": [
        "Danggogae",
        "Sanggye",
        "Nowon",
        "Chang-dong",
        "Ssangmun",
        "Suyu (Gangbuk-gu Office)",
        "Mia (Seoul Cyber University)",
        "Mia Sageori",
        "Gireum",
        "Sungshin Women's Univ. (Donam)",
        "Hansung Univ. (Samseongyo)",
        "Hyehwa",
        "Dongdaemun",
        "Dongdaemun History & Culture Park (DDP)",
        "Chungmuro",
        "Myeong-dong",
        "Hoehyeon (Namdaemun Market)",
        "Seoul Station",
        "Sookmyung Women's Univ. (Galwol)",
        "Samgakji (War Memorial of Korea)",
        "Sinyongsan",
        "Ichon (National Museum of Korea)",
        "Dongjak (National Cemetery)",
        "Chongshin Univ. (Isu)",
        "Sadang",
        "Namtaeryeong",
        "Seonbawi",
        "Seoul Racecourse Park",
        "Seoul Grand Park",
        "Gwacheon",
        "Government Complex Gwacheon",
        "Indeogwon",
        "Pyeongchon",
        "Beomgye",
        "Geumjeong",
        "Sanbon",
        "Surisan",
        "Daeyami",
        "Banwol",
        "Sangnoksu",
        "Hanyang Univ. at Ansan",
        "Jungang",
        "Gojan",
        "Choji",
        "Ansan",
        "Singil Oncheon",
        "Jeongwang",
        "Oido",
    ],

    # ── 5호선 (Line 5) ─────────────────────────────────────────────────────
    "Line 5": [
        "Banghwa",
        "Gaehwasan",
        "Gimpo International Airport",
        "Songjeong",
        "Magok",
        "Balsan",
        "Ujangsan",
        "Hwagok",
        "Kkachisan",
        "Sinjeong (Bank Area)",
        "Mok-dong",
        "Omokgyo (Mokdong Stadium)",
        "Yangpyeong",
        "Yeongdeungpo District Office",
        "Yeongdeungpo Market",
        "Singil",
        "Yeouido",
        "Yeouinaru",
        "Mapo",
        "Gongdeok",
        "Aeogae",
        "Chungjeongno (Kyonggi Univ.)",
        "Seodaemun",
        "Gwanghwamun (Sejong Center)",
        "Jongno 3(sam)-ga",
        "Euljiro 4(sa)-ga",
        "Dongdaemun History & Culture Park (DDP)",
        "Cheonggu",
        "Singeumho",
        "Haengdang",
        "Wangsimni (Seongdong-gu Office)",
        "Majang",
        "Dapsimni",
        "Janghanpyeong",
        "Gunja (Neungdong)",
        "Achasan (Children's Grand Park Rear Gate)",
        "Gwangnaru (Korea Baptist Theological Univ.)",
        "Cheonho (Pungnap Fortress)",
        "Gangdong",
        "Gildong",
        "Gubeundari (Gangdong Community Center)",
        "Myeongil",
        "Godeok",
        "Sangil-dong",
        "Gangil",
        "Misa",
        "Hanam Pungsan",
        "Hanam City Hall (Deokpung–Sinjang)",
        "Hanam Geomdansan",
        # Macheon branch (splits at Gangdong)
        "둔촌동",  # Dunchon-dong
        "Olympia Park (Korea National Sport Univ.)",
        "Bangi",
        "Gaerong",
        "Geoyeo",
        "Macheon",
    ],

    # ── 6호선 (Line 6) ─────────────────────────────────────────────────────
    "Line 6": [
        "Eungam",
        "Yeokchon",
        "Bulgwang",
        "Dokbawi",
        "Yeonsinnae",
        "Gusan",
        "Saejeol (Sinsa)",
        "Jeungsan (Myongji Univ.)",
        "Digital Media City",
        "World Cup Stadium (Seongsan)",
        "Mapo-gu Office",
        "Mangwon",
        "Hapjeong",
        "Sangsu",
        "Gwangheungchang (Sogang Univ.)",
        "Daeheung (Sogang Univ. Front)",
        "Gongdeok",
        "Hyochang Park",
        "Samgakji (War Memorial of Korea)",
        "Noksapyeong (Yongsan District Office)",
        "Itaewon",
        "Hangangjin",
        "Beotigogae",
        "Yaksu",
        "Cheonggu",
        "Sindang",
        "Dongmyo",
        "Changsin",
        "Bomun",
        "Anam (Korea Univ. Hospital)",
        "Korea Univ. (Jongam)",
        "Wolgok (Dongduk Women's Univ.)",
        "Sangwolgok (KIST)",
        "Dolgoji",
        "Seokgye",
        "Taereung Entrance",
        "Hwarangdae (Seoul Women's Univ.)",
        "Bonghwasan (Seoul Medical Center)",
        "Sinnae",
    ],

    # ── 7호선 (Line 7) ─────────────────────────────────────────────────────
    "Line 7": [
        "Jangam",
        "Dobongsan",
        "Suraksan",
        "Madeul",
        "Nowon",
        "Junggye",
        "Hagye",
        "Gongneung (SeoulTech)",
        "Taereung Entrance",
        "Meokgol",
        "Junghwa",
        "Sangbong",
        "Myeonmok",
        "Sagajeong",
        "Yongmasan (Yongma Falls Park)",
        "Junggok",
        "Gunja (Neungdong)",
        "Children's Grand Park (Sejong Univ.)",
        "Konkuk Univ",
        "Jayang (Ttukseom Hangang Park)",
        "Cheongdam",
        "Gangnam-gu Office",
        "Hakdong",
        "Nonhyeon",
        "Banpo",
        "Express Bus Terminal",
        "Naebang",
        "Isu",
        "Namseong",
        "Soongsil Univ. (Salpijae)",
        "Sangdo",
        "Jangseungbaegi",
        "Sindaebangsamgeori",
        "Boramae",
        "Sinpung",
        "Daerim (Guro-gu Office)",
        "Namguro",
        "Gasan Digital Complex",
        "Cheolsan",
        "Gwangmyeong Sageori",
        "Cheonwang",
        "Onsu (Sungkonghoe Univ.)",
        "Bucheon Stadium",
        "Wonjong",
        "Seongnam",
    ],

    # ── 8호선 (Line 8) ─────────────────────────────────────────────────────
    "Line 8": [
        "Amsa Historic Park",
        "Amsa",
        "Cheonho (Pungnap Fortress)",
        "Gangdong-gu Office",
        "Mongchontoseong (Peace Gate)",
        "Jamsil (Songpa-gu Office)",
        "Seokchon",
        "Songpa",
        "Garak Market",
        "Munjeong",
        "Jangji",
        "Bokjeong",
        "Nam Wirye",
        "Sanseong",
        "Namhansanseong Entrance (Seongnam Court & Prosecutors' Office)",
        "Dandae Ogeori",
        "Sinheung",
        "Sujin",
        "Moran",
    ],

    # ── 9호선 (Line 9) ─────────────────────────────────────────────────────
    "Line 9": [
        "Gaehwa",
        "Gimpo International Airport",
        "Airport Market",
        "Sinbanghwa",
        "Magoknaru (Seoul Botanic Park)",
        "Yangcheon Hyanggyo",
        "Gayang",
        "Jeungmi",
        "Deungchon",
        "Yeomchang",
        "Sinmokdong",
        "Seonyudo",
        "Dangsan",
        "National Assembly",
        "Yeouido",
        "Saetgang",
        "Noryangjin",
        "Nodeul",
        "Heukseok (Chung-Ang Univ.)",
        "Dongjak (National Cemetery)",
        "Gubanpo",
        "Sinbanpo",
        "Express Bus Terminal",
        "Sapyeong",
        "Sinnonhyeon",
        "Eonju",
        "Seonjeongneung",
        "Samseong Jungang",
        "Bongeunsa",
        "Sports Complex",
        "Samjeon",
        "Seokchon Ancient Tombs",
        "Seokchon",
        "Songpa Naru",
        "Hanseong Baekje",
        "Olympic Park (Korea National Sport Univ.)",
        "Dunchon Oryun",
        "Central Veterans Hospital",
    ],

    # Line 9 Phase 2-3 is a continuation; merged into Line 9 above.
    "Line 9, Phases 2–3": [
        "Express Bus Terminal",
        "Sapyeong",
        "Sinnonhyeon",
        "Eonju",
        "Seonjeongneung",
        "Samseong Jungang",
        "Bongeunsa",
        "Sports Complex",
        "Samjeon",
        "Seokchon Ancient Tombs",
        "Seokchon",
        "Songpa Naru",
        "Hanseong Baekje",
        "Olympic Park (Korea National Sport Univ.)",
        "Dunchon Oryun",
        "Central Veterans Hospital",
    ],

    # ── 경의선 (Gyeongui Line) ───────────────────────────────────────────────
    # Runs as part of Gyeongui–Jungang through-service; northwest section
    "Gyeongui Line": [
        "Munsan",
        "Imjingang",
        "Uncheon",
        "Paju",
        "Wollong",
        "Geumchon",
        "Geumneung",
        "Unjeong",
        "Yadang",
        "Tanhyeon",
        "Ilsan",
        "Pungsan",
        "Baengma",
        "Goksan",
        "Daegok",
        "Neunggok",
        "Neunggok",
        "Haengsin",
        "Gangmae",
        "Korea Aerospace Univ.",
        "Susaek",
        "Gajwa",
        "Digital Media City",
        "Hongik University",
        "Sogang Univ.",
        "Gongdeok",
        "Yongsan",
        "Seobinggo",
        "Hannam",
        "Oksu",
        "Eungbong",
        "Wangsimni (Seongdong-gu Office)",
        "Hoegi",
    ],

    # ── 경춘선 (Gyeongchun Line) ─────────────────────────────────────────────
    "Gyeongchun Line": [
        "Cheongnyangni (University of Seoul)",
        "Hoegi",
        "Jungnang",
        "Sangbong",
        "Mangu",
        "Sinnae",
        "Galmae",
        "Byeollae",
        "Toegyewon",
        "Sareung",
        "Geumgok",
        "Pyeongnae-Hopyeong",
        "Cheonmasan",
        "Maseok",
        "Daeseong-ri",
        "Cheongpyeong",
        "Sangcheon",
        "Gapyeong",
        "Gulbongsan",
        "Baegyang-ri",
        "Gangchon",
        "Kim Yu-jeong",
        "Namchuncheon",
        "Chuncheon",
    ],

    # ── 분당선 (Bundang Line) / 수인선 (Suin Line) → Suin–Bundang combined ──
    # CSV has separate entries: '분당선' = 'Bundang Line', '수인선' = 'Suin Line'
    "Bundang Line": [
        "Cheongnyangni (University of Seoul)",
        "Wangsimni (Seongdong-gu Office)",
        "Seoul Forest",
        "Apgujeong Rodeo",
        "Gangnam-gu Office",
        "Seonjeongneung",
        "Seolleung",
        "Hanti",
        "Dogok",
        "Guryong",
        "Gaepo-dong",
        "Daemosan Entrance",
        "Suseo",
        "Bokjeong",
        "Gachon Univ.",
        "Taepyeong",
        "Moran",
        "Yatap",
        "Imae",
        "Seohyeon",
        "Sunae",
        "Jeongja",
        "Migeum",
        "Ori",
        "Jukjeon",
        "Bojeong",
        "Guseong",
        "Singal",
        "Giheung",
        "Sanggal",
        "Cheongmyeong",
        "Yeongtong",
        "Mangpo",
        "Maetan-Gwonseon",
        "Suwon City Hall",
        "Maegyo",
        "Suwon",
    ],

    "Suin Line": [
        "Suwon",
        "Gosaek",
        "Omokcheon",
        "Eocheon",
        "Yamok",
        "Sari",
        "Hanyang Univ. at Ansan",
        "Jungang",
        "Gojan",
        "Choji",
        "Ansan",
        "Singil Oncheon",
        "Jeongwang",
        "Oido",
        "Darwol",
        "Wolgot",
        "Soraepogu",
        "Incheon Nonhyeon",
        "Hogupo",
        "Namdong Industrial Park",
        "Woninjae",
        "Yeonsu",
        "Songdo",
        "Inha Univ.",
        "Sungui",
        "Sinpo",
        "Incheon",
    ],

    # ── 공항철도 (Airport Railroad / AREX) ──────────────────────────────────
    "Airport Railroad (AREX)": [
        "Seoul Station",
        "Gongdeok",
        "Hongik University",
        "Digital Media City",
        "Magoknaru (Seoul Botanic Park)",
        "Gimpo International Airport",
        "Gyeyang",
        "Geomam",
        "Cheongna International City",
        "Yeongjong",
        "Unseo",
        "Airport Cargo Terminal",
        "Incheon Airport Terminal 1",
        "Incheon Airport Terminal 2",
    ],

    # ── 경강선 (Gyeonggang Line) ──────────────────────────────────────────
    "Gyeonggang Line": [
        "Pangyo",
        "Imae",
        "Samdong",
        "Gyeonggi Gwangju",
        "Chowol",
        "Gonjiam",
        "Sindun Ceramic Village",
        "Icheon",
        "Bubal",
        "King Sejong's Tomb",
        "Yeoju",
    ],

    # ── 서해선 (Seohae Line) ──────────────────────────────────────────────
    "Seohae Line": [
        "Ilsan",
        "Pungsan",
        "Baengma",
        "Goksan",
        "Daegok",
        "Neunggok",
        "Gimpo International Airport",
        "Wonjong",
        "Bucheon Stadium",
        "Sosa",
        "Bucheon",  # Sosaeul in some references — not in your CSV
        "Sari",
        "Oido",  # southern terminus via Siheung — check CSV exact names
    ],

    # ── 신림선 (Sillim Line) ──────────────────────────────────────────────
    "Sillim Line": [
        "Saetgang",
        "Daebang",
        "Seoul Military Manpower Office",
        "Boramae",
        "Boramae Park",
        "Boramae Medical Center",
        "Danggok",
        "Sillim",
        "Seowon",
        "Seoul Nat'l Univ. Venture Town",
        "Gwanaksan (Seoul Nat'l Univ.)",
    ],

    # ── 안산선 (Ansan Line) — shares track with Line 4 south of Geumjeong ──
    "Ansan Line": [
        "Geumjeong",
        "Sanbon",
        "Surisan",
        "Daeyami",
        "Banwol",
        "Sangnoksu",
        "Hanyang Univ. at Ansan",
        "Jungang",
        "Gojan",
        "Choji",
        "Ansan",
        "Singil Oncheon",
        "Jeongwang",
        "Oido",
    ],

    # ── 과천선 (Gwacheon Line) — shares track with Line 4 ─────────────────
    "Gwacheon Line": [
        "Seoul Station",
        "Sookmyung Women's Univ. (Galwol)",
        "Samgakji (War Memorial of Korea)",
        "Sinyongsan",
        "Ichon (National Museum of Korea)",
        "Dongjak (National Cemetery)",
        "Chongshin Univ. (Isu)",
        "Sadang",
        "Namtaeryeong",
        "Seonbawi",
        "Seoul Racecourse Park",
        "Seoul Grand Park",
        "Gwacheon",
        "Government Complex Gwacheon",
        "Indeogwon",
        "Pyeongchon",
        "Beomgye",
        "Geumjeong",
    ],

    # ── 우이신설선 (Ui-Sinseol Line) ──────────────────────────────────────
    "Ui-Sinseol Line": [
        "Bukhansan Ui",
        "Solbat Park",
        "April 19 National Cemetery",
        "Gaori",
        "Hwagye",
        "Samyang",
        "Samyang Sageori",
        "Solsaem",
        "Bukhansan Bogungmun",
        "Jeongneung",
        "Sungshin Women's Univ.",
        "Bomun",
        "Sinseol-dong",
    ],

    # ── 일산선 (Ilsan Line) — part of Line 3 through service ──────────────
    "Ilsan Line": [
        "Daehwa",
        "Juyeop",
        "Jeongbalsan",
        "Madu",
        "Baekseok",
        "Daegok",
        "Hwajeong",
        "Wondang",
        "Wonheung",
        "Samsong",
        "Jichuk",
        "Gupabal",
        "Yeonsinnae",
        "Bulgwang",
        "Nokbeon",
        "Hongje",
        "Muakjae",
        "Dongnimmun",
        "Gyeongbokgung (Government Complex Seoul)",
        "Anguk",
        "Jongno 3(sam)-ga",
    ],

    # ── 중앙선 (Jungang Line) ─────────────────────────────────────────────
    "Jungang Line": [
        "Yongmun",
        "Wondeok",
        "Obin",
        "Asin",
        "Guksu",
        "Sinwon",
        "Yangsu",
        "Ungilsan",
        "Paldang",
        "Dosim",
        "Deokso",
        "Yangjeong",
        "Donong",
        "Guri",
        "Yangwon",
        "Mangu",
        "Sangbong",
        "Jungnang",
        "Hoegi",
        "Hankuk Univ. of Foreign Studies",
        "Sinimun",
        "Eungbong",
        "Wangsimni (Seongdong-gu Office)",
        "Oksu",
        "Hannam",
        "Seobinggo",
        "Yongsan",
        "Gongdeok",
        "Sogang Univ.",
        "Hongik University",
        "Digital Media City",
        "Susaek",
        "Korea Aerospace Univ.",
        "Gangmae",
        "Haengsin",
        "Neunggok",
        "Daegok",
        "Goksan",
        "Baengma",
        "Pungsan",
        "Ilsan",
        "Tanhyeon",
        "Yadang",
        "Unjeong",
        "Geumneung",
        "Geumchon",
        "Wollong",
        "Paju",
        "Munsan",
        "Imjingang",
        "Jipyeong",
    ],

    # ── 장항선 (Janghang Line) ────────────────────────────────────────────
    "Janghang Line": [
        "Cheonan",
        "Bongmyeong",
        "Ssangyong (Nazareth Univ.)",
        "Asan",
        "Tangjeong",
        "Baebang",
        "Onyang Oncheon",
        "Sinchang (Soonchunhyang Univ.)",
    ],
}


def get_sorted_stations(route_name_en, df_agg):
    """
    Return stations for a given RouteNameEn in correct line order.
    Falls back to original CSV order if line not in STATION_ORDER.

    Args:
        route_name_en: string matching RouteNameEn in the CSV
        df_agg: aggregated DataFrame with columns [RouteNameEn, StationNameEn, ...]

    Returns:
        list of StationNameEn in correct order
    """
    group = df_agg[df_agg["RouteNameEn"] == route_name_en]["StationNameEn"].tolist()

    if route_name_en not in STATION_ORDER:
        print(f"[WARN] No order defined for '{route_name_en}', using CSV order.")
        return group

    reference = STATION_ORDER[route_name_en]
    # Only keep stations that actually exist in the data
    ordered = [s for s in reference if s in group]
    # Append any stations in data but not in reference (shouldn't happen often)
    missing = [s for s in group if s not in reference]
    if missing:
        print(f"[WARN] {route_name_en}: stations not in reference order: {missing}")
        ordered += missing

    return ordered