STATION_ORDER = {
    # Line 1 – main line + 4 branches
    "Line 1": [
        # Gyeongwon Line (north) – extended to Yeoncheon
        [
            "Yeoncheon",
            "Jeongok",
            "Cheongsan",
            "Soyosan",
            "Dongducheon",
            "Bosan",
            "Dongducheon Jungang",
            "Jihaeng",
            "Deokjeong",
            "Deokgye",
            "Yangju",
            "Nogyang",
            "Ganeung",
            "Uijeongbu",
            "Hoeryong",
            "Mangwolsa",
            "Dobongsan",
            "Dobong",
            "Banghak",
            "Chang-dong",
            "Nokcheon",
            "Wolgye",
            "Kwangwoon Univ.",
            "Seokgye",
            "Sinimun",
            "Hankuk Univ. of Foreign Studies",
            "Hoegi",
            "Cheongnyangni (University of Seoul)",
            "Jegi-dong",
            "Sinseol-dong",
            "Dongmyo",
            "Dongdaemun",
            "Jongno 5(o)-ga",
            "Jongno 3-ga",
            "Jonggak",
            "City Hall",
            "Seoul Station",
            "Namyeong",
            "Yongsan",
            "Noryangjin",
            "Daebang",
            "Singil",
            "Yeongdeungpo",
            "Sindorim",
            "Guro",
            "Gasan Digital Complex",
            "Doksan",
            "Geumcheon-gu Office",
            "Seoksu",
            "Gwanak",
            "Anyang",
            "Myeonghak",
            "Geumjeong",
            "Gunpo",
            "Uiwang",
            "Sungkyunkwan Univ.",
            "Hwaseo",
            "Suwon",
            "Seryu",
            "Byeongjeom",
            "Sema",
            "Osan Univ.",
            "Osan",
            "Jinwi",
            "Songtan",
            "Seojeong-ri",
            "Pyeongtaek Jije",
            "Pyeongtaek",
            "Seonghwan",
            "Jiksan",
            "Dujeong",
            "Cheonan",
            "Bongmyeong",
            "Ssangyong (Nazareth Univ.)",
            "Asan",
            "Tangjeong",
            "Baebang",
            "Onyang Oncheon",
            "Sinchang (Soonchunhyang Univ.)",
        ],
        # Gyeongin branch (from Guro) – added missing stations
        [
            "Guro",
            "Guil",
            "Gaebong",
            "Oryudong",
            "Yeokgok",
            "Sosa",
            "Bucheon",
            "Jung-dong",
            "Songnae",
            "Bugae",
            "Bupyeong",
            "Baegun",
            "Dongam",
            "Ganseok",
            "Juan",
            "Dohwa",
            "Jemulpo",
            "Dowon",
            "Dongincheon",
            "Incheon",
        ],
        # Byeongjeom branch
        ["Byeongjeom", "Seodongtan"],
        # Gwangmyeong shuttle
        ["Geumcheon-gu Office", "Gwangmyeong"],
    ],
    "Line 2": [
        # Main loop (City Hall → … → City Hall)
        [
            "City Hall",
            "Euljiro 1(il)-ga",
            "Euljiro 3(sam)-ga",
            "Euljiro 4(sa)-ga",
            "Dongdaemun History & Culture Park (DDP)",
            "Sindang",
            "Sangwangsimni",
            "Wangsimni (Seongdong-gu Office)",
            "Hanyang University",
            "Ttukseom",
            "Seongsu",
            "Konkuk Univ",
            "Guui (Gwangjin-gu Office)",
            "Gangbyeon (East Seoul Bus Terminal)",
            "Jamsilnaru",
            "Jamsil (Songpa-gu Office)",
            "Jamsilsaenae",
            "Sports Complex",
            "Samseong (World Trade Center)",
            "Seolleung",
            "Yeoksam",
            "Gangnam",
            "Seoul Nat'l Univ. of Education",
            "Seocho",
            "Bangbae",
            "Sadang",
            "Nakseongdae (Gang Gam-chan)",
            "Seoul Nat'l Univ. (Gwanak-gu Office)",
            "Bongcheon",
            "Sillim",
            "Sindaebang",
            "Guro Digital Complex",
            "Daerim (Guro-gu Office)",
            "Mullae",
            "Yeongdeungpo District Office",
            "Dangsan",
            "Hapjeong",
            "Hongik University",
            "Sinchon",
            "Ewha Womans University",
            "Ahyeon",
            "Chungjeongno (Kyonggi Univ.)",
            "City Hall",
        ],
        # Seongsu branch
        ["Seongsu", "Yongdap", "Sindap", "Sinseol-dong"],
        # Sinjeong branch
        [
            "Mullae",
            "Sindorim",
            "Dorimcheon",
            "Yangcheon-gu Office",
            "Sinjeongnegeori",
            "Kkachisan",
        ],
    ],
    # Line 3 – no branches
    "Line 3": [
        [
            "Daehwa",
            "Juyeop",
            "Jeongbalsan",
            "Madu",
            "Baekseok",
            "Daegok",
            "Hwajeong",
            "Wondang",
            "Wonheung",
            "Samsong",
            "Jichuk",
            "Gupabal",
            "Yeonsinnae",
            "Bulgwang",
            "Nokbeon",
            "Hongje",
            "Muakjae",
            "Dongnimmun",
            "Gyeongbokgung (Government Complex Seoul)",
            "Anguk",
            "Jongno 3(sam)-ga",
            "Euljiro 3(sam)-ga",
            "Chungmuro",
            "Dongguk Univ.",
            "Yaksu",
            "Geumho",
            "Oksu",
            "Apgujeong",
            "Sinsa",
            "Jamwon",
            "Express Bus Terminal",
            "Seoul Nat'l Univ. of Education",
            "Nambu Bus Terminal (Seoul Arts Center)",
            "Yangjae (Seocho-gu Office)",
            "Maebong",
            "Dogok",
            "Daechi",
            "Hangnyeoul",
            "Daecheong",
            "Irwon",
            "Suseo",
            "Garak Market",
            "Police Hospital",
            "Ogeum",
        ]
    ],
    # Line 4 – no branches
    "Line 4": [
        [
            "Bulamsan",
            "Sanggye",
            "Nowon",
            "Chang-dong",
            "Ssangmun",
            "Suyu (Gangbuk-gu Office)",
            "Mia (Seoul Cyber University)",
            "Mia Sageori",
            "Gireum",
            "Sungshin Women's Univ. (Donam)",
            "Hansung Univ. (Samseongyo)",
            "Hyehwa",
            "Dongdaemun",
            "Dongdaemun History & Culture Park (DDP)",
            "Chungmuro",
            "Myeong-dong",
            "Hoehyeon (Namdaemun Market)",
            "Seoul Station",
            "Sookmyung Women's Univ. (Galwol)",
            "Samgakji (War Memorial of Korea)",
            "Sinyongsan",
            "Ichon (National Museum of Korea)",
            "Dongjak (National Cemetery)",
            "Chongshin Univ. (Isu)",
            "Sadang",
            "Namtaeryeong",
            "Seonbawi",
            "Seoul Racecourse Park",
            "Seoul Grand Park",
            "Gwacheon",
            "Government Complex Gwacheon",
            "Indeogwon",
            "Pyeongchon",
            "Beomgye",
            "Sanbon",
            "Surisan",
            "Daeyami",
            "Banwol",
            "Sangnoksu",
            "Hanyang Univ. at Ansan",
            "Jungang",
            "Gojan",
            "Choji",
            "Ansan",
            "Singil Oncheon",
            "Jeongwang",
            "Oido",
        ]
    ],
    # Line 5 – main line + Hanam branch
    "Line 5": [
        # Main line (Banghwa → Macheon)
        [
            "Banghwa",
            "Gaehwasan",
            "Gimpo International Airport",
            "Songjeong",
            "Magok",
            "Balsan",
            "Ujangsan",
            "Hwagok",
            "Kkachisan",
            "Sinjeong (Bank Area)",
            "Mok-dong",
            "Omokgyo (Mokdong Stadium)",
            "Yangpyeong",
            "Yeongdeungpo District Office",
            "Yeongdeungpo Market",
            "Singil",
            "Yeouido",
            "Yeouinaru",
            "Mapo",
            "Gongdeok",
            "Aeogae",
            "Chungjeongno (Kyonggi Univ.)",
            "Seodaemun",
            "Gwanghwamun (Sejong Center)",
            "Jongno 3(sam)-ga",
            "Euljiro 4(sa)-ga",
            "Dongdaemun History & Culture Park (DDP)",
            "Cheonggu",
            "Singeumho",
            "Haengdang",
            "Wangsimni (Seongdong-gu Office)",
            "Majang",
            "Dapsimni",
            "Janghanpyeong",
            "Gunja (Neungdong)",
            "Achasan (Children's Grand Park Rear Gate)",
            "Gwangnaru (Korea Baptist Theological Univ.)",
            "Cheonho (Pungnap Fortress)",
            "Gangdong",
            "Gildong",
            "Gubeundari (Gangdong Community Center)",
            "Myeongil",
            "Godeok",
            "Sangil-dong",
            "Misa",
            "Hanam Pungsan",
            "Hanam City Hall (Deokpung–Sinjang)",
            "Hanam Geomdansan",
        ],
        # Hanam branch (from Gangdong)
        [
            "Gangdong",
            "Dunchon-dong",
            "Olympic Park (Korea National Sport Univ.)",
            "Bangi",
            "Ogeum",
            "Gaerong",
            "Geoyeo",
            "Macheon",
        ],
    ],
    # Line 6 – no branches
    "Line 6": [
        [
            "Eungam",
            "Saejeol (Sinsa)",
            "Jeungsan (Myongji Univ.)",
            "Digital Media City",
            "World Cup Stadium (Seongsan)",
            "Mapo-gu Office",
            "Mangwon",
            "Hapjeong",
            "Sangsu",
            "Gwangheungchang (Sogang Univ.)",
            "Daeheung (Sogang Univ. Front)",
            "Gongdeok",
            "Hyochang Park",
            "Samgakji (War Memorial of Korea)",
            "Noksapyeong (Yongsan District Office)",
            "Itaewon",
            "Hangangjin",
            "Beotigogae",
            "Yaksu",
            "Cheonggu",
            "Sindang",
            "Dongmyo",
            "Changsin",
            "Bomun",
            "Anam (Korea Univ. Hospital)",
            "Korea Univ. (Jongam)",
            "Wolgok (Dongduk Women's Univ.)",
            "Sangwolgok (KIST)",
            "Dolgoji",
            "Seokgye",
            "Taereung Entrance",
            "Hwarangdae (Seoul Women's Univ.)",
            "Bonghwasan (Seoul Medical Center)",
            "Yeonsinnae",
            "Sinnae",
        ],
        [
            "Eungam",
            "Yeokchon",
            "Bulgwang",
            "Dokbawi",
            "Gusan",
            "Eungam",
        ],
    ],
    # Line 7 – no branches
    "Line 7": [
        [
            "Jangam",
            "Dobongsan",
            "Suraksan",
            "Madeul",
            "Nowon",
            "Junggye",
            "Hagye",
            "Gongneung (SeoulTech)",
            "Taereung Entrance",
            "Meokgol",
            "Junghwa",
            "Sangbong",
            "Myeonmok",
            "Sagajeong",
            "Yongmasan (Yongma Falls Park)",
            "Junggok",
            "Gunja (Neungdong)",
            "Children's Grand Park (Sejong Univ.)",
            "Konkuk Univ",
            "Jayang (Ttukseom Hangang Park)",
            "Cheongdam",
            "Gangnam-gu Office",
            "Hakdong",
            "Nonhyeon",
            "Banpo",
            "Express Bus Terminal",
            "Naebang",
            "Isu",
            "Namseong",
            "Soongsil Univ. (Salpijae)",
            "Sangdo",
            "Jangseungbaegi",
            "Sindaebangsamgeori",
            "Boramae",
            "Sinpung",
            "Daerim (Guro-gu Office)",
            "Namguro",
            "Gasan Digital Complex",
            "Cheolsan",
            "Gwangmyeong Sageori",
            "Cheonwang",
            "Onsu (Sungkonghoe Univ.)",
        ]
    ],
    # Line 8 – no branches
    "Line 8": [
        [
            "Amsa Historic Park",
            "Amsa",
            "Cheonho (Pungnap Fortress)",
            "Gangdong-gu Office",
            "Mongchontoseong (Peace Gate)",
            "Jamsil (Songpa-gu Office)",
            "Seokchon",
            "Songpa",
            "Garak Market",
            "Munjeong",
            "Jangji",
            "Bokjeong",
            "Nam Wirye",
            "Sanseong",
            "Namhansanseong Entrance (Seongnam Court & Prosecutors' Office)",
            "Dandae Ogeori",
            "Sinheung",
            "Sujin",
            "Moran",
        ]
    ],
    # Line 9 – no branches
    "Line 9": [
        [
            "Gaehwa",
            "Gimpo International Airport",
            "Airport Market",
            "Sinbanghwa",
            "Magoknaru (Seoul Botanic Park)",
            "Yangcheon Hyanggyo",
            "Gayang",
            "Jeungmi",
            "Deungchon",
            "Yeomchang",
            "Sinmokdong",
            "Seonyudo",
            "Dangsan",
            "National Assembly",
            "Yeouido",
            "Saetgang",
            "Noryangjin",
            "Nodeul",
            "Heukseok (Chung-Ang Univ.)",
            "Dongjak (National Cemetery)",
            "Gubanpo",
            "Sinbanpo",
            "Express Bus Terminal",
            "Sapyeong",
            "Sinnonhyeon",
            "Eonju",
            "Seonjeongneung",
            "Samseong Jungang",
            "Bongeunsa",
            "Sports Complex",
            "Samjeon",
            "Seokchon Ancient Tombs",
            "Seokchon",
            "Songpa Naru",
            "Hanseong Baekje",
            "Olympic Park (Korea National Sport Univ.)",
            "Dunchon Oryun",
            "Central Veterans Hospital",
        ]
    ],
    # Airport Railroad – no branches
    "Airport Railroad (AREX)": [
        [
            "Seoul Station",
            "Gongdeok",
            "Hongik University",
            "Digital Media City",
            "Magoknaru (Seoul Botanic Park)",
            "Gimpo International Airport",
            "Gyeyang",
            "Geomam",
            "Cheongna International City",
            "Unseo",
            "Airport Cargo Terminal",
            "Incheon Airport Terminal 1",
            "Incheon Airport Terminal 2",
            "Yeongjong",
        ]
    ],
    # Gyeongchun Line – no branches
    "Gyeongchun Line": [
        [
            "Sinnae",
            "Galmae",
            "Byeollae",
            "Toegyewon",
            "Sareung",
            "Geumgok",
            "Pyeongnae-Hopyeong",
            "Cheonmasan",
            "Maseok",
            "Daeseong-ri",
            "Cheongpyeong",
            "Sangcheon",
            "Gapyeong",
            "Gulbongsan",
            "Baegyang-ri",
            "Gangchon",
            "Kim Yu-jeong",
            "Namchuncheon",
            "Chuncheon",
        ]
    ],
    # Seohae Line – partial
    "Seohae Line": [["Gimpo International Airport", "Wonjong", "Bucheon Stadium"]],
    # Sillim Line – no branches
    "Sillim Line": [
        [
            "Saetgang",
            "Daebang",
            "Seoul Military Manpower Office",
            "Boramae",
            "Boramae Park",
            "Boramae Medical Center",
            "Danggok",
            "Sillim",
            "Seowon",
            "Seoul Nat'l Univ. Venture Town",
            "Gwanaksan (Seoul Nat'l Univ.)",
        ]
    ],
    # Ui-Sinseol Line – no branches
    "Ui-Sinseol Line": [
        [
            "Bukhansan Ui",
            "Solbat Park",
            "April 19 National Cemetery",
            "Gaori",
            "Hwagye",
            "Samyang",
            "Samyang Sageori",
            "Solsaem",
            "Bukhansan Bogungmun",
            "Jeongneung",
            "Sungshin Women's Univ. (Donam)",
            "Bomun",
            "Sinseol-dong",
        ]
    ],
    # Suin-Bundang Line – complex, but treat as a single branch (it's essentially one line now)
    "Suin-Bundang Line": [
        # Already includes the missing stations; ensure exact names:
        [
            "Incheon",
            "Sinpo",
            "Sungui",
            "Inha Univ.",
            "Songdo",
            "Yeonsu",
            "Woninjae",
            "Namdong Industrial Park",
            "Hogupo",
            "Incheon Nonhyeon",
            "Soraepogu",
            "Wolgot",
            "Darwol",
            "Sari",
            "Yamok",
            "Eocheon",
            "Omokcheon",
            "Gosaek",
            "Suwon",
            "Maegyo",
            "Suwon City Hall",
            "Maetan-Gwonseon",
            "Mangpo",
            "Yeongtong",
            "Cheongmyeong",
            "Sanggal",
            "Giheung",
            "Singal",
            "Guseong",
            "Bojeong",
            "Jukjeon",
            "Ori",
            "Migeum",
            "Jeongja",
            "Sunae",
            "Seohyeon",
            "Imae",
            "Yatap",
            "Moran",
            "Taepyeong",
            "Gachon Univ.",
            "Suseo",
            "Daemosan Entrance",
            "Gaepo-dong",
            "Guryong",
            "Dogok",
            "Hanti",
            "Seolleung",
            "Seonjeongneung",
            "Gangnam-gu Office",
            "Apgujeong Rodeo",
            "Seoul Forest",
            "Wangsimni (Seongdong-gu Office)",
        ]
    ],
    # Gyeongui-Jungang Line – main line + Yeoju branch
    "Gyeongui-Jungang Line": [
        # Main line (Munsan → Jipyeong) – added Imjingang and Uncheon
        [
            "Imjingang",
            "Uncheon",
            "Munsan",
            "Paju",
            "Wollong",
            "Geumchon",
            "Geumneung",
            "Unjeong",
            "Yadang",
            "Tanhyeon",
            "Ilsan",
            "Pungsan",
            "Baengma",
            "Goksan",
            "Neunggok",
            "Haengsin",
            "Gangmae",
            "Korea Aerospace Univ.",
            "Susaek",
            "Digital Media City",
            "Gajwa",
            "Hongik University",
            "Sogang Univ.",
            "Gongdeok",
            "Hyochang Park",
            "Yongsan",
            "Ichon (National Museum of Korea)",
            "Seobinggo",
            "Hannam",
            "Oksu",
            "Eungbong",
            "Wangsimni (Seongdong-gu Office)",
            "Cheongnyangni",
            "Hoegi",
            "Jungnang",
            "Sangbong",
            "Mangu",
            "Yangwon",
            "Guri",
            "Donong",
            "Yangjeong",
            "Deokso",
            "Dosim",
            "Paldang",
            "Ungilsan",
            "Yangsu",
            "Sinwon",
            "Guksu",
            "Asin",
            "Obin",
            "Yangpyeong",
            "Wondeok",
            "Yongmun",
            "Jipyeong",
        ],
    ],
    "Gyuonggang Line": [
        [
            "Pangyo",
            "Seongnam",
            "Imae",
            "Samdong",
            "Gyeonggi Gwangju",
            "Chowol",
            "Gonjiam",
            "Sindun Ceramic Village",
            "Icheon",
            "Bubal",
            "King Sejong's Tomb",
            "Yeoju",
        ]
    ],
}
